# Ativa o console do banco H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Banco de Dados em Memória
spring.datasource.url=jdbc:h2:mem:libratsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostra o SQL no console (Para você ver o Spring trabalhando!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true